---
- name: "Install fail2ban"
  ansible.builtin.package:
    name: fail2ban
    state: latest

- name: "Update fail2ban defaults"
  ansible.builtin.command:
    argv:
      - update-rc.d
      - fail2ban
      - defaults
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_major_version | int >= 12

- name: "Set logtarget to systemd journal"
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/fail2ban.conf
    regexp: "^logtarget = *"
    line: "logtarget = SYSTEMD-JOURNAL"

- name: "Copy jail configuration into place"
  template:
    src: "jail.conf.tmpl"
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644

- name: "Enable fail2ban on init and start it"
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: "Change default SSH port to {{ security_ssh_port }}"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#Port 22"
    line: "Port {{ security_ssh_port }}"

- name: "Update SSH configuration to be more secure"
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
  with_items:
    - regexp: "^#PasswordAuthentication yes"
      line: "PasswordAuthentication no"
    - regexp: "^#PermitEmptyPasswords no"
      line: "PermitEmptyPasswords no"
    - regexp: "^#PubkeyAuthentication yes"
      line: "PubkeyAuthentication yes"

- name: "Restart SSH server"
  ansible.builtin.service:
    name: ssh
    state: restarted
